<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert(
            collect([
                //Ligas
                ['nombre' => 'Liga de patada',                  'slug' => 'Liga-de-patada',                     'mayoreo' => 0, 'precio' => 342.00,     'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 1,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Barra de poder',                  'slug' => 'Barra-de-poder',                     'mayoreo' => 0, 'precio' => 672.00,     'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 1,'ancho' => 3,'alto' => 12, 'largo' => 50, 'peso' => 1.04],
                ['nombre' => 'Liga forrada',                    'slug' => 'Liga-forrada',                       'mayoreo' => 0, 'precio' => 165.00,     'precio_mayoreo' => null,   'variante' => 1,    'category_id' => 1,'ancho' => 15,'alto' => 7 , 'largo' => 19, 'peso' => 0.14],
                ['nombre' => 'Liga 1 1/2m ',                    'slug' => 'Liga-1-1-2m',                        'mayoreo' => 0, 'precio' => 136.00,     'precio_mayoreo' => null,   'variante' => 1,    'category_id' => 1,'ancho' => 11,'alto' => 6, 'largo' => 16, 'peso' => 0.16],
                ['nombre' => 'Liga 1 metro ',                   'slug' => 'Liga-1-metro',                       'mayoreo' => 0, 'precio' => 95.00,      'precio_mayoreo' => null,   'variante' => 1,    'category_id' => 1,'ancho' => 11,'alto' => 7, 'largo' => 12, 'peso' => 0.123],
                ['nombre' => 'Liga tipo 8 cerrada',             'slug' => 'Liga-tipo-8-cerrada',                'mayoreo' => 0, 'precio' => 68.00,      'precio_mayoreo' => null,   'variante' => 1,    'category_id' => 1,'ancho' => 9,'alto' => 6, 'largo' => 11, 'peso' => 0.1],
                ['nombre' => 'Kit de ligas',                    'slug' => 'Kit-de-ligas',                       'mayoreo' => 0, 'precio' => 280.00,     'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 1,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Grilletes con liga 3D',           'slug' => 'Grilletes-con-liga-3D',              'mayoreo' => 0, 'precio' => 416.00,     'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 1,'ancho' => 10,'alto' => 8, 'largo' => 17, 'peso' => 0.36],
                ['nombre' => 'Bandas de resistencia premium',   'slug' => 'Bandas-de-resistencia-premium',      'mayoreo' => 0, 'precio' => 370.00,     'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 1,'ancho' => 7,'alto' => 8, 'largo' => 13, 'peso' => 0.35],
                ['nombre' => 'Liga strop',                      'slug' => 'Liga-strop',                         'mayoreo' => 0, 'precio' => 705.00,     'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 1,'ancho' => 15,'alto' => 8, 'largo' => 19, 'peso' => 0.256],
                ['nombre' => 'Cinturón Liga strop',             'slug' => 'Cinturon-Liga-strop',                'mayoreo' => 0, 'precio' => 250.00,     'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 1,'ancho' => 10,'alto' => 3, 'largo' => 44, 'peso' => 0.323],
                ['nombre' => 'Liga de abducción',               'slug' => 'Liga-de-abduccion',                  'mayoreo' => 0, 'precio' => 165.00,     'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 1,'ancho' => 8,'alto' => 4, 'largo' => 15, 'peso' => 0.8],
                ['nombre' => 'Wear bands',                      'slug' => 'Wear-bands',                         'mayoreo' => 0, 'precio' => 706.00,     'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 1,'ancho' => 22,'alto' => 11, 'largo' => 50, 'peso' => 1.25],
                ['nombre' => 'Liga de tobillo ',                'slug' => 'Liga-de-tobillo',                    'mayoreo' => 0, 'precio' => 188.00,     'precio_mayoreo' => null,   'variante' => 1,    'category_id' => 1,'ancho' => 8,'alto' => 5, 'largo' => 15, 'peso' => 0.11],
                ['nombre' => 'Bandas de resistencia de latex',  'slug' => 'Bandas-de-resistencia-de-latex',     'mayoreo' => 0, 'precio' => 297.00,     'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 1,'ancho' => 8,'alto' => 4, 'largo' => 13, 'peso' => 0.24],
                ['nombre' => '5 en 1 funcional',                'slug' => '5-en-1-funcional',                   'mayoreo' => 0, 'precio' => 672.00,     'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 1,'ancho' => null,'alto' => null, 'largo' => null, 'peso' =>null ],
                ['nombre' => 'Bungee beg',                      'slug' => 'Bungee-beg',                         'mayoreo' => 1, 'precio' => 3225.00,    'precio_mayoreo' => null,   'variante' => 1,    'category_id' => 1,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                //paquete de bongies mayoreo
                ['nombre' => 'Banda de pilates',                'slug' => 'Banda-de-pilates',                   'mayoreo' => 0, 'precio' => 220.00,     'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 1,'ancho' => 9,'alto' => 3, 'largo' => 12, 'peso' => 0.11],
                ['nombre' => 'Cinturón glúteo y pierna',        'slug' => 'Cinturon-gluteo-y-pierna',           'mayoreo' => 0, 'precio' => 556.00,     'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 1,'ancho' => 16,'alto' => 11, 'largo' => 31, 'peso' => 0.44],
                //['nombre' => '', 'slug' => '',               'mayoreo' => 0, 'precio' => , 'precio_mayoreo' => null, 'category_id' => 1],

                //maquinas
                ['nombre' => 'Banco 90 grados',                     'slug' => 'Banco-90-grados',                    'mayoreo' => 0, 'precio' => 3250.00,    'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 2,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Banco plano',                         'slug' => 'Banco-plano',                        'mayoreo' => 0, 'precio' => 3250.00,    'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 2,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Crossover V',                         'slug' => 'Crossover-V',                        'mayoreo' => 0, 'precio' => 33500.00,   'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 2,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Sentadilla Sissy',                    'slug' => 'Sentadilla-Sissy',                   'mayoreo' => 0, 'precio' => 4400.00,    'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 2,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Piso de alto impacto',                'slug' => 'Piso-de-alto-impacto',               'mayoreo' => 0, 'precio' => 596.00,     'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 2,'ancho' => 53,'alto' => 4, 'largo' => 53, 'peso' => 14],
                ['nombre' => 'Escaladora reacondicionada',          'slug' => 'Escaladora-reacondicionada',         'mayoreo' => 0, 'precio' => 4300.00,    'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 2,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Hip trust',                           'slug' => 'Hip-trust',                          'mayoreo' => 0, 'precio' => 11500.00,   'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 2,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Banco de posiciones',                 'slug' => 'Banco-de-posiciones',                'mayoreo' => 0, 'precio' => 4100.00,    'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 2,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Hip trust con cinturón',              'slug' => 'Hip-trust-con-cinturon',             'mayoreo' => 0, 'precio' => 14500.00,   'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 2,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Banco recto, inclinado o reclinado',  'slug' => 'Banco-recto-inclinado-o-reclinado',  'mayoreo' => 0, 'precio' => 9500.00,    'precio_mayoreo' => null,   'variante' => 0,    'category_id' => 2,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                //['nombre' => '', 'slug' => '',               'mayoreo' => 0, 'precio' => , 'precio_mayoreo' => null, 'category_id' => 2],

                //Funcional Crossfit
                ['nombre' => 'conos',                                                       'slug' => 'conos',                                                  'mayoreo' => 0, 'precio' => 34.00,      'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 14,'alto' => 25, 'largo' => 14, 'peso' => 0.115],
                ['nombre' => 'platos',                                                      'slug' => 'platos',                                                 'mayoreo' => 0, 'precio' => 29.00,      'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 20,'alto' => 5.5, 'largo' => 20, 'peso' => 0.038],
                ['nombre' => 'Balón con agarres 5kg',                                       'slug' => 'Balon-con-agarres-5kg',                                  'mayoreo' => 0, 'precio' => 973.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 35,'alto' => 35, 'largo' => 35, 'peso' => 5],
                ['nombre' => 'Mancuerna hexagonal dumbell',                                 'slug' => 'Mancuerna-hexagonal-dumbell',                            'mayoreo' => 0, 'precio' => 520.00,     'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 16,'alto' => 16, 'largo' => 35, 'peso' => 2.267],
                ['nombre' => 'Farmer cross olímpico pintura horneada',                      'slug' => 'Farmer-cross-olimpico-pintura-horneada',                 'mayoreo' => 0, 'precio' => 2423,       'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Farmer cross olímpico pintura cromada',                       'slug' => 'Farmer-cross-olimpico-pintura-cromada',                  'mayoreo' => 0, 'precio' => 2550,       'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Farmer cross estándar pintura horneada',                      'slug' => 'Farmer-cross-estandar-pintura-horneada',                 'mayoreo' => 0, 'precio' => 2156,       'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Farmer cross estándar pintura cromada',                       'slug' => 'Farmer-cross-estandar-pintura-cromada',                  'mayoreo' => 0, 'precio' => 2238,       'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Kit polainas en libras',                                      'slug' => 'Kit-polainas-en-libras',                                 'mayoreo' => 0, 'precio' => 2290,       'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 30,'alto' => 18, 'largo' => 26, 'peso' => 9.307],
                ['nombre' => 'Cuerdas de salto',                                            'slug' => 'Cuerdas-de-salto',                                       'mayoreo' => 0, 'precio' => 31,         'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 9,'alto' => 7, 'largo' => 17, 'peso' => 0.25],
                ['nombre' => 'Mancuerna redonda',                                           'slug' => 'Mancuerna-redonda',                                      'mayoreo' => 0, 'precio' => 194,        'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 7,'alto' => 7, 'largo' => 16, 'peso' => 0.5],
                ['nombre' => 'Rack dumbell',                                                'slug' => 'Rack-dumbell',                                           'mayoreo' => 0, 'precio' => 13400.00,   'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Escalera de agilidad',                                        'slug' => 'Escalera-de-agilidad',                                   'mayoreo' => 0, 'precio' => 586,        'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Trineo de arrastre olímpico',                                 'slug' => 'Trineo-de-arrastre-olimpico',                            'mayoreo' => 0, 'precio' => 1499.00,    'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Barra estandar 150 cm solido',                                'slug' => 'Barra-estandar-solido',                                  'mayoreo' => 0, 'precio' => 2319,       'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 7,'alto' => 7, 'largo' => 150, 'peso' => 2.425],
                ['nombre' => 'Barra estandar 150 cm hueca',                                 'slug' => 'Barra-estandar-hueca',                                   'mayoreo' => 0, 'precio' => 990,        'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 4.5,'alto' => 4.5, 'largo' => 150, 'peso' => 2.425],
                ['nombre' => 'Aros olímpicos',                                              'slug' => 'Aros-olimpicos',                                         'mayoreo' => 0, 'precio' => 927.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 25,'alto' => 7, 'largo' => 25, 'peso' => 2.4],
                ['nombre' => 'Trineo de empuje y arrastre',                                 'slug' => 'Trineo-de-empuje-y-arrastre',                            'mayoreo' => 0, 'precio' => 3653.00,    'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Cuerda de velocidad sencilla',                                'slug' => 'Cuerda-de-velocidad-sencilla',                           'mayoreo' => 0, 'precio' => 139,        'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 4,'alto' => 3, 'largo' => 13, 'peso' => 0.165],
                ['nombre' => 'Costal de box sin relleno',                                   'slug' => 'Costal-de-box-sin-relleno',                              'mayoreo' => 0, 'precio' => 150,        'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Costal de box',                                               'slug' => 'Costal-de-box',                                          'mayoreo' => 0, 'precio' => 788,       'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Mancuerna estándar x kilo',                                   'slug' => 'Mancuerna-estandar-x-kilo',                              'mayoreo' => 0, 'precio' => 78.00,      'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 16,'alto' => 16, 'largo' => 25, 'peso' => 2],
                ['nombre' => 'Straps para abdominales',                                     'slug' => 'Straps-para-abdominales',                                'mayoreo' => 0, 'precio' => 853.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' =>null , 'largo' => null, 'peso' =>null],
                ['nombre' => 'Sandbag',                                                     'slug' => 'Sandbag',                                                'mayoreo' => 0, 'precio' => 1368.00,    'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 24,'alto' => 24, 'largo' => 67, 'peso' => 9.071],
                ['nombre' => 'Polainas manos',                                              'slug' => 'Polainas-manos',                                         'mayoreo' => 0, 'precio' => 203,        'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Polainas pierna',                                             'slug' => 'Polainas-pierna',                                        'mayoreo' => 0, 'precio' => 202,        'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 29,'alto' => 12, 'largo' => 40, 'peso' => 0.5],
                ['nombre' => 'Polainas ajustables par',                                     'slug' => 'Polainas-ajustables-par',                                'mayoreo' => 0, 'precio' => 672,        'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 29,'alto' => 12, 'largo' => 45, 'peso' => 5],
                ['nombre' => 'Rack para mancuernas 9 pares sencillo sin soportes',          'slug' => 'Rack-para-mancuernas-9-pares-sencillo-sin-soportes',     'mayoreo' => 0, 'precio' => 4500,       'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Rack para mancuernas 9 pares profesional con soportes',       'slug' => 'Rack-para-mancuernas-9-pares-profesional-con-soportes',  'mayoreo' => 0, 'precio' => 6800,       'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Cinturón hip trust BEG',                                      'slug' => 'Cinturon-hip-trust-BEG',                                 'mayoreo' => 0, 'precio' => 452.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 14,'alto' => 3, 'largo' => 36, 'peso' => 0.2],
                ['nombre' => 'Landmine 2 en 1',                                             'slug' => 'Landmine-2-en-1',                                        'mayoreo' => 0, 'precio' => 1750.00,    'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 30,'alto' => 13, 'largo' => 48, 'peso' => 4.4],
                ['nombre' => 'Tapete funcional',                                            'slug' => 'Tapete-funcional',                                       'mayoreo' => 0, 'precio' => 266.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 9,'alto' => 9, 'largo' => 60, 'peso' => 0.35],
                ['nombre' => 'Barra olímpica',                                              'slug' => 'Barra-olimpica',                                         'mayoreo' => 0, 'precio' => 2679,       'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 8,'alto' => 8, 'largo' => 150, 'peso' => 20],
                ['nombre' => 'Barra olímpica 150cm x 1 in hueca',                           'slug' => 'Barra-olimpica-150cm-1-in-hueca',                        'mayoreo' => 0, 'precio' => 1159,       'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 10,'alto' => 10, 'largo' => 150, 'peso' => 9.725],
                ['nombre' => '2 en 1',                                                      'slug' => '2-en-1',                                                 'mayoreo' => 0, 'precio' => 1790.00,    'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Battle rope 9m',                                              'slug' => 'Battle-rope-9m',                                         'mayoreo' => 0, 'precio' => 1860.00,    'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 41,'alto' => 27, 'largo' => 41, 'peso' => 10.65],
                ['nombre' => 'Pesa rusa x lb',                                              'slug' => 'Pesa-rusa-x-lb',                                         'mayoreo' => 0, 'precio' => 37,         'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 16,'alto' => 26, 'largo' => 19, 'peso' => 2.267],
                ['nombre' => 'Disco dumbell kit 10 discos',                                 'slug' => 'Disco-dumbell-kit-10-discos',                            'mayoreo' => 0, 'precio' => 15680.00,   'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' =>null, 'largo' => null, 'peso' =>null ],
                ['nombre' => 'Balón medicinal',                                             'slug' => 'Balon-medicinal',                                        'mayoreo' => 0, 'precio' => 590,        'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 30,'alto' => 30, 'largo' => 30, 'peso' => 3],
                ['nombre' => 'Set de 3 bancos',                                             'slug' => 'Set-3-bancos',                                           'mayoreo' => 0, 'precio' => 3525,       'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Bancos de salto',                                             'slug' => 'Bancos-de-salto',                                        'mayoreo' => 0, 'precio' => 1008,       'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Cuerda de batalla 1.5in',                                     'slug' => 'Cuerda-de-batalla-1.5in',                                'mayoreo' => 0, 'precio' => 242,        'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 28,'alto' => 5, 'largo' => 28, 'peso' => 0.44],
                ['nombre' => 'Cuadro de entrenamiento',                                     'slug' => 'Cuadro-de-entrenamiento',                                'mayoreo' => 0, 'precio' => 590.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 32,'alto' => 6, 'largo' => 32, 'peso' => 1.05],
                ['nombre' => 'Mancuerna plastificada',                                      'slug' => 'Mancuerna-plastificada',                                 'mayoreo' => 0, 'precio' => 196,        'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 11,'alto' => 11, 'largo' => 30, 'peso' => 0.5],
                ['nombre' => 'Cinturón ruso',                                               'slug' => 'Cinturon-ruso',                                          'mayoreo' => 0, 'precio' => 451.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 12,'alto' => 5, 'largo' => 42, 'peso' => 0.3],
                ['nombre' => 'Saco búlgaro',                                                'slug' => 'Saco-bulgaro',                                           'mayoreo' => 0, 'precio' => 1095.00,    'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Gato elevador de peso muerto',                                'slug' => 'Gato-elevador-de-peso-muerto',                           'mayoreo' => 0, 'precio' => 1950.00,    'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Disco estándar/olímpico x kg',                                'slug' => 'Disco-estandar-olimpico-x-kg',                           'mayoreo' => 0, 'precio' => 72.00,      'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 25,'alto' => 3, 'largo' => 25, 'peso' => 1],
                ['nombre' => 'Barra con peso fijo',                                         'slug' => 'Barra-con-peso-fijo',                                    'mayoreo' => 0, 'precio' => 367,        'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 3,'alto' => 3, 'largo' => 60, 'peso' => 3],
                ['nombre' => 'Set 3 bases para gemelos',                                    'slug' => 'Set-3-bases-para-gemelos',                               'mayoreo' => 0, 'precio' => 440,        'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 11,'alto' => 15, 'largo' => 31, 'peso' => 0.37],
                ['nombre' => 'Banda de suspensión tipo trx',                                'slug' => 'Banda-de-suspension-tipo-trx',                           'mayoreo' => 0, 'precio' => 1066.00,    'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 17,'alto' => 9, 'largo' => 28, 'peso' => 0.5],
                ['nombre' => 'Arnes de cabeza',                                             'slug' => 'Arnes-de-cabeza',                                        'mayoreo' => 0, 'precio' => 556,        'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 17,'alto' => 4, 'largo' => 28, 'peso' => 0.31],
                ['nombre' => 'Cuerda de velocidad mango de aluminio',                       'slug' => 'Cuerda-de-velocidad-mango-de-aluminio',                  'mayoreo' => 0, 'precio' => 305.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 4,'alto' => 3, 'largo' => 13, 'peso' => 0.165],
                ['nombre' => 'Liga pull ups',                                               'slug' => 'Liga-pull-ups',                                          'mayoreo' => 0, 'precio' => 350,        'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 5,'alto' => 3, 'largo' => 27, 'peso' => 0.26],
                ['nombre' => 'Slam ball',                                                   'slug' => 'Slam-ball',                                              'mayoreo' => 0, 'precio' => 650,        'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 28,'alto' => 28, 'largo' => 28, 'peso' => 3.628],
                ['nombre' => 'Dommy chico',                                                 'slug' => 'Dommy-ch',                                               'mayoreo' => 0, 'precio' => 610,        'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 14,'alto' => 42, 'largo' => 35, 'peso' => 0.595],
                ['nombre' => 'Dommy grande',                                                'slug' => 'Dommy-g',                                                'mayoreo' => 0, 'precio' => 680,        'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 14,'alto' => 57, 'largo' => 35, 'peso' => 1],
                ['nombre' => 'Barras paralelas',                                            'slug' => 'Barras-paralelas',                                       'mayoreo' => 0, 'precio' => 1043,       'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Pesa rusa plastificada x lb',                                 'slug' => 'Pesa-rusa-plastificada-x-lb',                            'mayoreo' => 0, 'precio' => 50,         'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => 16,'alto' => 26, 'largo' => 19, 'peso' => 2.267],
                ['nombre' => 'Rack para pesa rusa',                                         'slug' => 'Rack-para-pesa-rusa',                                    'mayoreo' => 0, 'precio' => 4500,       'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 3,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                //['nombre' => '', 'slug' => '',               'mayoreo' => 0, 'precio' => , 'precio_mayoreo' => null, 'category_id' => 3],


                //Agarres y cojines
                ['nombre' => 'Agarre dorsal',                   'slug' => 'Agarre-dorsal',                                                                      'mayoreo' => 0, 'precio' => 916.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 3,'alto' => 11, 'largo' => 117, 'peso' => 5],
                ['nombre' => 'Agarre largo recto pala',         'slug' => 'Agarre-largo-recto-pala',                                                            'mayoreo' => 0, 'precio' => 1200.00,    'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 3,'alto' => 16, 'largo' => 98, 'peso' => 5],
                ['nombre' => 'Agarre largo para crossover',     'slug' => 'Agarre-largo-para-crossover',                                                        'mayoreo' => 0, 'precio' => 400.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 10,'alto' => 8, 'largo' => 14, 'peso' => 0.4],
                ['nombre' => 'Agarre doble D',                  'slug' => 'Agarre-doble-D',                                                                     'mayoreo' => 0, 'precio' => 522.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 16,'alto' => 17, 'largo' => 14, 'peso' => 1.8],
                ['nombre' => 'Agarre v',                        'slug' => 'Agarre-v',                                                                           'mayoreo' => 0, 'precio' => 522.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 5,'alto' => 23, 'largo' => 27, 'peso' => 1.8],
                ['nombre' => 'Agarre bigote',                   'slug' => 'Agarre-bigote',                                                                      'mayoreo' => 0, 'precio' => 916.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 3,'alto' => 8, 'largo' => 66, 'peso' => 3],
                ['nombre' => 'Agarre dorsal largo pala',        'slug' => 'Agarre-dorsal-largo-pala',                                                           'mayoreo' => 0, 'precio' => 1350.00,    'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 15,'alto' => 20, 'largo' => 125, 'peso' => 5],
                ['nombre' => 'Cojín protector con cintas',      'slug' => 'Cojin-protector-con-cintas',                                                         'mayoreo' => 0, 'precio' => 325.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 10,'alto' => 10, 'largo' => 42, 'peso' => 0.235],
                ['nombre' => 'Cojín protector para barra',      'slug' => 'Cojin-protector-para-barra',                                                         'mayoreo' => 0, 'precio' => 231.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 9,'alto' => 9, 'largo' => 37, 'peso' => 0.13],
                ['nombre' => 'Agarre recto corto',              'slug' => 'Agarre-recto-corto',                                                                 'mayoreo' => 0, 'precio' => 522.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 3,'alto' => 9, 'largo' => 40, 'peso' => 1.8],
                ['nombre' => 'Agarradera pala',                 'slug' => 'Agarradera-pala',                                                                    'mayoreo' => 0, 'precio' => 750.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 6,'alto' => 15, 'largo' => 15, 'peso' => 1.6],
                ['nombre' => 'Agarre de cuerda',                'slug' => 'Agarre-de-cuerda',                                                                   'mayoreo' => 0, 'precio' => 525.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 7,'alto' => 35, 'largo' => 14, 'peso' => 0.6],
                ['nombre' => 'Jaladera sencilla',               'slug' => 'Jaladera-sencilla',                                                                  'mayoreo' => 0, 'precio' => 650.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 5,'alto' => 16, 'largo' => 16, 'peso' => 1.8],
                ['nombre' => 'Cuerda tríceps 1 agarre',         'slug' => 'Cuerda-triceps-1-agarre',                                                            'mayoreo' => 0, 'precio' => 320.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 7,'alto' => 35, 'largo' => 7, 'peso' => 0.27],
                ['nombre' => 'Agarre v pala',                   'slug' => 'Agarre-v-pala',                                                                      'mayoreo' => 0, 'precio' => 750.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 16,'alto' => 19, 'largo' => 22, 'peso' => 2.25],
                ['nombre' => 'Agarres multiusos',               'slug' => 'Agarres-multiusos',                                                                  'mayoreo' => 0, 'precio' => 222.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 9,'alto' => 6, 'largo' => 11, 'peso' => 0.21],
                ['nombre' => 'Cuerda para tríceps sencilla',    'slug' => 'Cuerda-para-triceps-sencilla',                                                       'mayoreo' => 0, 'precio' => 231.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 6,'alto' => 3, 'largo' => 35, 'peso' => 0.105],
                ['nombre' => 'Agarres premium',                 'slug' => 'Agarres-premium',                                                                    'mayoreo' => 0, 'precio' => 4871.00,    'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 4,'ancho' => 13,'alto' => 18, 'largo' => 96, 'peso' => 14.6],
                //['nombre' => '', 'slug' => '',               'mayoreo' => 0, 'precio' => , 'precio_mayoreo' => null, 'category_id' => 4],

                //Fitness
                ['nombre' => 'Deslizadores',                    'slug' => 'Deslizadores',                           'mayoreo' => 0, 'precio' => 226.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => 22,'alto' => 1.5, 'largo' => 22, 'peso' => 0.11],
                ['nombre' => 'Banco step de metal',             'slug' => 'Banco-step-de-metal',                    'mayoreo' => 0, 'precio' => 857.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => 30,'alto' => 11, 'largo' => 60, 'peso' => 5.27],
                ['nombre' => 'Balón suizo',                     'slug' => 'Balon-suizo',                            'mayoreo' => 0, 'precio' => 278.00,     'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => 21,'alto' => 11, 'largo' => 24, 'peso' => 0.77],
                //['nombre' => 'Balón suizo 55, 65 cm', lonitud              'slug' => 'Balon-suizo-65',                         'mayoreo' => 0, 'precio' => 349.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5],
                //['nombre' => 'Balón suizo 75 cm', lonitud              'slug' => 'Balon-suizo-75',                         'mayoreo' => 0, 'precio' => 397.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5],
                ['nombre' => 'Pelota de gel',                   'slug' => 'Pelota-de-gel',                          'mayoreo' => 0, 'precio' => 57.00,      'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => 13,'alto' => 13, 'largo' => 13, 'peso' => 0.5],
                //['nombre' => 'Pelota de gel 1/2,1 kg',    peso          'slug' => 'Pelota-de-gel-1kg',                      'mayoreo' => 0, 'precio' => 68.00,      'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5],
                //['nombre' => 'Pelota de gel 1 1/2 kg',peso          'slug' => 'Pelota-de-gel-1-1-2kg',                  'mayoreo' => 0, 'precio' => 80.00,      'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5],
                //['nombre' => 'Pelota de gel 2 kg',    peso          'slug' => 'Pelota-de-gel-2kg',                      'mayoreo' => 0, 'precio' => 92.00,      'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5],
                //['nombre' => 'Pelota de gel 3 kg',    peso          'slug' => 'Pelota-de-gel-3kg',                      'mayoreo' => 0, 'precio' => 115.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5],
                //['nombre' => 'Pelota de gel 4 kg',    peso          'slug' => 'Pelota-de-gel-4kg',                      'mayoreo' => 0, 'precio' => 157.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5],
                ['nombre' => 'Banco step de madera',            'slug' => 'Banco-step-de-madera',                   'mayoreo' => 0, 'precio' => 650.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => 30,'alto' => 10, 'largo' => 60, 'peso' => 3.4],
                ['nombre' => 'Tapete fitness',                  'slug' => 'Tapete-fitness',                         'mayoreo' => 0, 'precio' => 189.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Mancuernas fitness ',        'slug' => 'Mancuernas-fitness',                     'mayoreo' => 0, 'precio' => 196,        'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => 3,'alto' => 3, 'largo' => 20, 'peso' => 0.5],
                //['nombre' => 'Mancuernas fitness 1/2kg 1kg', peso         'slug' => 'Mancuernas-fitness-1kg',                 'mayoreo' => 0, 'precio' => 219,        'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5],
                ['nombre' => 'Paquete fitness',                 'slug' => 'Paquete-fitness',                        'mayoreo' => 0, 'precio' => 314.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => 17,'alto' => 13, 'largo' => 17, 'peso' => 2.1],
                ['nombre' => 'Jumping uso rudo',                'slug' => 'Jumping-uso-rudo',                       'mayoreo' => 0, 'precio' => 2799,       'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Jumping uso rudo jumbo',          'slug' => 'Jumping-uso-rudo-jumbo',                 'mayoreo' => 0, 'precio' => 3249,       'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Baquetas tono básico',            'slug' => 'Baquetas-tono-basico',                   'mayoreo' => 0, 'precio' => 103,        'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => 5,'alto' => 3, 'largo' => 41, 'peso' => 0.19],
                ['nombre' => 'Baquetas tono neón',              'slug' => 'Baquetas-tono-neon',                     'mayoreo' => 0, 'precio' => 122,        'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => 5,'alto' => 3, 'largo' => 41, 'peso' => 0.19],
                ['nombre' => 'Baquetas tono metálico',          'slug' => 'Baquetas-tono-metalico',                 'mayoreo' => 0, 'precio' => 122,        'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => 5,'alto' => 3, 'largo' => 41, 'peso' => 0.19],
                ['nombre' => 'Slide beg',                       'slug' => 'Slide-beg',                              'mayoreo' => 0, 'precio' => 885.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => 13,'alto' => 16, 'largo' => 55, 'peso' => 2],
                ['nombre' => 'Banco step plástico 2 alturas',   'slug' => 'Banco-step-plastico-2-alturas',          'mayoreo' => 0, 'precio' => 760.00,     'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => 9,'alto' => 28, 'largo' => 63, 'peso' => 2.32],
                ['nombre' => 'Jumping importado',               'slug' => 'Jumping-importado',                      'mayoreo' => 0, 'precio' => 1975.00,    'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Banco step 2 alturas ',           'slug' => 'Banco-step-2-alturas',                   'mayoreo' => 0, 'precio' => 1450,       'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 5,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],



                //Refacciones
                ['nombre' => 'Selector de peso',                                'slug' => 'Selector-de-peso',                           'mayoreo' => 1, 'precio' => 87.00,          'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 5 ,'alto' => 1, 'largo' => 15, 'peso' =>0.07 ],
                //3/8 y 5/16 longitud
                ['nombre' => 'Forro cubre resortes (refaccion jumping)',        'slug' => 'Forro-cubre-resortes',                       'mayoreo' => 0, 'precio' => 290,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 15,'alto' => 9, 'largo' => 19, 'peso' => 0.125],
                ['nombre' => 'Base T (refaccion jumping)',                      'slug' => 'Base-T',                                     'mayoreo' => 0, 'precio' => 360,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 39,'alto' => 4, 'largo' => 121, 'peso' => 1.9],
                ['nombre' => 'Malla trampolín (refaccion jumping)',             'slug' => 'Malla-trampolin',                            'mayoreo' => 0, 'precio' => 750,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 36,'alto' => 5, 'largo' => 36, 'peso' =>0.365 ],
                ['nombre' => 'Resorte estándar (refaccion jumping)',            'slug' => 'Resorte-estandar',                           'mayoreo' => 0, 'precio' => 32,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 1.5,'alto' => 1.5, 'largo' => 9, 'peso' => 0.057],
                ['nombre' => 'Resorte bicónico (refaccion jumping)',            'slug' => 'Resorte-biconico',                           'mayoreo' => 0, 'precio' => 39,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 3,'alto' => 3, 'largo' => 9, 'peso' => 0.092],
                ['nombre' => 'Liga x metro (refaccion jumping)',                'slug' => 'Liga-x-metro',                               'mayoreo' => 0, 'precio' => 40,             'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                // longitudes
                ['nombre' => 'Bigote (refaccion jumping)',                      'slug' => 'Bigote',                                     'mayoreo' => 0, 'precio' => 32,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 1.5,'alto' => 0.5, 'largo' => 11, 'peso' => 0.032],
                ['nombre' => 'Regaton para pata (refaccion jumping)',           'slug' => 'Regaton-para-pata',                          'mayoreo' => 0, 'precio' => 17,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 4,'alto' => 3.5, 'largo' => 4, 'peso' =>0.032 ],
                ['nombre' => 'Pata completa (refaccion jumping)',               'slug' => 'Pata-completa',                              'mayoreo' => 0, 'precio' => 175,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 4,'alto' => 4, 'largo' => 18, 'peso' =>0.3 ],
                ['nombre' => 'Reparación de malla (refaccion jumping)',         'slug' => 'Reparacion-de-malla',                        'mayoreo' => 0, 'precio' => 280,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Balero (refacción caminadora)',                   'slug' => 'Balero',                                     'mayoreo' => 0, 'precio' => 84,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 5,'alto' => 1, 'largo' => 5, 'peso' =>0.119 ],
                ['nombre' => 'Cadena (refacción caminadora)',                   'slug' => 'Cadena',                                     'mayoreo' => 0, 'precio' => 227,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 13,'alto' => 3, 'largo' => 15, 'peso' =>1.32 ],
                ['nombre' => 'Candado (refacción caminadora)',                  'slug' => 'Candado',                                    'mayoreo' => 0, 'precio' => 27,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 1.5,'alto' => 1, 'largo' => 2, 'peso' => 0.008],
                ['nombre' => 'Perno (refacción caminadora)',                    'slug' => 'Perno',                                      'mayoreo' => 0, 'precio' => 92,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 1.5,'alto' => 1.5, 'largo' => 6.5, 'peso' => 0.068],
                ['nombre' => 'Catarina (refacción caminadora)',                 'slug' => 'Catarina',                                   'mayoreo' => 0, 'precio' => 447,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 8.5,'alto' => 2.5, 'largo' => 8.5, 'peso' => 0.725],
                ['nombre' => 'Buje (refacción caminadora)',                     'slug' => 'Buje',                                       'mayoreo' => 0, 'precio' => 27,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 5,'alto' => 3.5, 'largo' => 5, 'peso' => 0.029],
                ['nombre' => 'Huella par (refacción caminadora)',               'slug' => 'Huella',                                     'mayoreo' => 0, 'precio' => 245,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 10,'alto' => 5, 'largo' => 36, 'peso' =>1.1 ],
                ['nombre' => 'Nivelador (refacción caminadora)',                'slug' => 'Nivelador',                                  'mayoreo' => 0, 'precio' => 21,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 4,'alto' => 4, 'largo' => 4, 'peso' => 0.028],
                ['nombre' => 'Portavaso (refacción caminadora)',                'slug' => 'Portavaso',                                  'mayoreo' => 0, 'precio' => 110,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 11,'alto' => 13, 'largo' => 11, 'peso' => 0.19],
                ['nombre' => 'Llanta par (refacción caminadora)',               'slug' => 'Llanta',                                     'mayoreo' => 0, 'precio' => 45,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 5,'alto' => 5, 'largo' => 5, 'peso' => 0.07],
                ['nombre' => 'Buje p/ catarina (refacción caminadora)',         'slug' => 'Buje-p-catarina',                            'mayoreo' => 0, 'precio' => 30,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 1.5,'alto' => 1, 'largo' => 1.5, 'peso' => 0.016],
                ['nombre' => 'Amortiguadores par (refacción caminadora)',       'slug' => 'Amortiguadores',                             'mayoreo' => 0, 'precio' => 990,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => null,'alto' => null , 'largo' => null , 'peso' => null ],
                ['nombre' => 'Liga jumbo (refacción bungee)',                   'slug' => 'Liga-jumbo',                                 'mayoreo' => 0, 'precio' => 1329,           'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 17,'alto' => 8, 'largo' => 47, 'peso' => 1.3],
                ['nombre' => 'Arnés (refacción bungee)',                        'slug' => 'Arnes',                                      'mayoreo' => 0, 'precio' => 1565,           'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 24,'alto' => 12, 'largo' => 47, 'peso' => 1],
                ['nombre' => 'Extensor (refacción bungee)',                     'slug' => 'Extensor',                                   'mayoreo' => 0, 'precio' => 297,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 13,'alto' => 4, 'largo' => 13, 'peso' =>0.32 ],
                ['nombre' => 'Bandola jumbo (refacción bungee)',                'slug' => 'Bandola-jumbo',                              'mayoreo' => 0, 'precio' => 80,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 4,'alto' => 1.5, 'largo' => 9, 'peso' => 0.128],
                ['nombre' => 'Anclaje (refacción bungee)',                      'slug' => 'Anclaje',                                    'mayoreo' => 0, 'precio' => 428,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 11,'alto' => 7, 'largo' => 11, 'peso' => 0.85],
                ['nombre' => 'Cable extresor 1.5m (refacción bungee)',          'slug' => 'Cable-extresor',                             'mayoreo' => 0, 'precio' => 265,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 21,'alto' => 2, 'largo' => 21, 'peso' => 0.225],
                ['nombre' => 'Tapa hongo cedula 30 y 40',                       'slug' => 'Tapa-hongo',                                 'mayoreo' => 1, 'precio' => 29.00,          'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 4,'alto' => 4, 'largo' => 4, 'peso' => 0.022],
                ['nombre' => 'Bandola',                                         'slug' => 'Bandola',                                  'mayoreo' => 1, 'precio' => 36.00,            'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 3.5,'alto' => 0.5, 'largo' => 7, 'peso' => 0.045],
                //['nombre' => 'Bandola #7cm  #8',  longitud   7 y 9 pueden ser del bungie                  'slug' => 'Bandola-8',                      'mayoreo' => 1, 'precio' => 43.00,              'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6],
                //['nombre' => 'Bandola #9',  longitud                    'slug' => 'Bandola-9',                      'mayoreo' => 1, 'precio' => 50.00,              'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6],
                //['nombre' => 'Bandola #10', longitud                    'slug' => 'Bandola-10',                     'mayoreo' => 1, 'precio' => 65.00,              'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6],
                ['nombre' => 'Herraje destorcedor',                             'slug' => 'Herraje-destorcedor',                        'mayoreo' => 1, 'precio' => 87,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 5,'alto' => 0.5, 'largo' => 9, 'peso' => 0.115],
                //destorcedor puede ser para bungee
                ['nombre' => 'Remache de aluminio 3/16',                        'slug' => 'Remache-de-aluminio-3-16',                   'mayoreo' => 1, 'precio' => 13,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 1.5,'alto' => 1, 'largo' => 2, 'peso' => 0.008],
                ['nombre' => 'Bandola de eslabon con seguro',                   'slug' => 'Bandola-de-eslabon-con-seguro',              'mayoreo' => 1, 'precio' => 87,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 4,'alto' => 1, 'largo' => 7, 'peso' => 0.05],
                ['nombre' => 'Guardacabo 3/16',                                 'slug' => 'Guardacabo-3-16',                            'mayoreo' => 1, 'precio' => 20,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 3,'alto' => 0.5, 'largo' => 4, 'peso' => 0.01],
                ['nombre' => 'Chapetón metálico',                               'slug' => 'Chapeton-metalico',                          'mayoreo' => 1, 'precio' => 41,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 3.5,'alto' => 0.5, 'largo' => 3.5, 'peso' => 0.021],
                ['nombre' => 'Puntas de poping',                                'slug' => 'Puntas-de-poping',                           'mayoreo' => 1, 'precio' => 47,             'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 3.5,'alto' => 1.5, 'largo' => 5, 'peso' => 0.022],
                //3/8 y 5/16 longitud
                ['nombre' => 'Puños uso rudo',                                  'slug' => 'Punos-uso-rudo',                             'mayoreo' => 1, 'precio' => 58.00,          'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 8,'alto' => 3.5, 'largo' => 12.5, 'peso' => 0.12],
                ['nombre' => 'Buje de uña',                                     'slug' => 'Buje-de-una',                                'mayoreo' => 1, 'precio' => 29.00,          'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 4,'alto' => 2, 'largo' => 4, 'peso' => 0.015],
                ['nombre' => 'Sistema para sentadilla smith',                   'slug' => 'Sistema-para-sentadilla-smith',              'mayoreo' => 1, 'precio' => 7600,           'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Kit sistema para sentadilla smith y guías',       'slug' => 'Kit-sistema-para-sentadilla-smith-y-guias',  'mayoreo' => 1, 'precio' => 13650,          'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Cinturón para elevación de pelvis',               'slug' => 'Cinturon-para-elevacion-de-pelvis',          'mayoreo' => 1, 'precio' => 1475.00,       'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Guías para prensa',                               'slug' => 'Guias-para-prensa',                          'mayoreo' => 1, 'precio' => 5500,           'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                // 1in y 1 1/4 lonigtud
                ['nombre' => 'Rodillo de tapicería',                            'slug' => 'Rodillo-de-tapiceria',                       'mayoreo' => 1, 'precio' => 240,            'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' =>12 ,'alto' => 12, 'largo' => 20, 'peso' => 0.95],
                //20 cm y 50 cm lonigtud
                ['nombre' => 'Bola de paso con prisionero',                     'slug' => 'Bola-de-paso-con-prisionero',                'mayoreo' => 1, 'precio' => 41,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 4,'alto' => 4, 'largo' => 4, 'peso' => 0.03],
                ['nombre' => 'Chumacera',                                       'slug' => 'Chumacera',                                  'mayoreo' => 1, 'precio' => 210,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 3,'alto' => 6.5, 'largo' => 12, 'peso' => 0.6],
                ['nombre' => 'Buje de sombrero 3/4',                            'slug' => 'Buje-de-sombrero',                           'mayoreo' => 1, 'precio' => 14,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 3.5,'alto' => 3, 'largo' => 3.5, 'peso' => 0.01],
                ['nombre' => 'Rodillo polipropileno',                           'slug' => 'Rodillo-polipropileno',                      'mayoreo' => 1, 'precio' => 290,            'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 12,'alto' => 12, 'largo' => 16, 'peso' => 0.3],
                ///tamaño o mayoreo
                ['nombre' => 'Poping',                                          'slug' => 'Poping',                                     'mayoreo' => 1, 'precio' => 175,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 5,'alto' => 2.5, 'largo' => 9.5, 'peso' => 0.2],
                ['nombre' => 'Puños premium',                                   'slug' => 'Punos-premium',                              'mayoreo' => 1, 'precio' => 220,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 6,'alto' => 3, 'largo' => 20, 'peso' => 0.15],
                ['nombre' => 'Llanta de prensa',                                'slug' => 'Llanta-de-prensa',                           'mayoreo' => 1, 'precio' => 185,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 6.5,'alto' => 3.5, 'largo' => 6.5, 'peso' => 0.19],
                ['nombre' => 'Cable uso rudo nylon x metro',                    'slug' => 'Cable-uso-rudo-nylon-x-metro',               'mayoreo' => 1, 'precio' => 50,             'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 28,'alto' => 0.35, 'largo' => 28, 'peso' => 0.055],
                //longitudes cable 
                ['nombre' => 'Cable uso rudo nylon bobina',                     'slug' => 'Cable-uso-rudo-nylon-bobina',                'mayoreo' => 1, 'precio' => 4800,           'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 24,'alto' => 22, 'largo' => 24, 'peso' =>9.2 ],
                ['nombre' => 'Opresor',                                         'slug' => 'Opresor',                                    'mayoreo' => 1, 'precio' => 185,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 4.5,'alto' => 5, 'largo' => 8, 'peso' => 0.3],
                ['nombre' => 'Chapetón de plástico',                            'slug' => 'Chapeton-de-plastico',                       'mayoreo' => 1, 'precio' => 29,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 9,'alto' => 1, 'largo' => 9, 'peso' => 0.029],
                ['nombre' => 'Chapetón para mancuerna',                         'slug' => 'Chapeton-para-mancuerna',                    'mayoreo' => 1, 'precio' => 87,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 10,'alto' => 1, 'largo' => 10, 'peso' => 0.155],
                ['nombre' => 'Bola de paso o tope',                             'slug' => 'Bola-de-paso-o-tope',                        'mayoreo' => 1, 'precio' => 20,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 3,'alto' => 3, 'largo' => 3, 'peso' => 0.017],
                ['nombre' => 'Soporte para barras doble',                       'slug' => 'Soporte-para-barras-doble',                  'mayoreo' => 1, 'precio' => 986,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 29,'alto' => 5, 'largo' => 41, 'peso' => 4],
                ['nombre' => 'Soporte para mancuernas',                         'slug' => 'Soporte-para-mancuernas',                    'mayoreo' => 1, 'precio' => 87,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 8,'alto' => 3, 'largo' => 14, 'peso' => 0.265],
                ['nombre' => 'Tapa para tornillo y tuerca 3/8',                 'slug' => 'Tapa-para-tornillo-y-tuerca',                'mayoreo' => 1, 'precio' => 8.50,           'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 2,'alto' => 1, 'largo' => 2, 'peso' => 0.002],
                ['nombre' => 'Tapa interna',                                    'slug' => 'Tapa-interna',                               'mayoreo' => 1, 'precio' => 20,             'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 5,'alto' => 1.5, 'largo' => 5, 'peso' => 0.02],
                //tamaño o mayoreo
                //['nombre' => 'sopporte con guias',                      'slug' => '',                      'mayoreo' => 0, 'precio' => ,              'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6],
                //no entiendo nada
                ['nombre' => 'Perilla de ajuste 1/2',                           'slug' => 'Perilla-de-ajuste-1-2',                      'mayoreo' => 1, 'precio' => 43,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 5,'alto' => 7, 'largo' => 6, 'peso' => 0.075],
                ['nombre' => 'Reductores',                                      'slug' => 'Reductores',                                 'mayoreo' => 1, 'precio' => 29,             'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 4.5,'alto' => 10, 'largo' => 4.5, 'peso' => 0.045],
                //2-1.5 y 2.5-2 tamaños
                ['nombre' => 'Camisa para discos',                              'slug' => 'Camisa-para-discos',                         'mayoreo' => 1, 'precio' => 330,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 7,'alto' => 30, 'largo' => 15, 'peso' => 1.5],
                ['nombre' => 'Tapa para tubo 1/2 cedula 30',                    'slug' => 'Tapa para tubo',                             'mayoreo' => 1, 'precio' => 18,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 5,'alto' => 1.5, 'largo' => 5, 'peso' => 0.015],
                ['nombre' => 'Buje metálico para polea o rueda',                'slug' => 'Buje-metalico-para-polea-o-rueda',           'mayoreo' => 1, 'precio' => 29,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 1.5,'alto' => 1, 'largo' => 1.5, 'peso' =>0.015 ],
                ['nombre' => 'Balero lineal',                                   'slug' => 'Balero-lineal',                              'mayoreo' => 1, 'precio' => 410,            'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 3.5,'alto' => 5.5, 'largo' => 3.5, 'peso' => 0.2],
                //lonigtud 1in y 1 1/4in y 1 1 1/2 in
                ['nombre' => 'Poleas',                                          'slug' => 'Poleas',                                     'mayoreo' => 1, 'precio' => 100,            'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                //longitud 3.5 y 4.5
                ['nombre' => 'Regatones',                                       'slug' => 'Regatones',                                  'mayoreo' => 1, 'precio' => 35,             'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 7,'alto' => 5.5, 'largo' => 7, 'peso' => 0.12],
                //tamaños o mayoreo
                ['nombre' => 'Dona de impacto 2in',                             'slug' => 'Dona-de-impacto-2in',                        'mayoreo' => 1, 'precio' => 29,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 7,'alto' => 2, 'largo' => 7, 'peso' => 0.064],
                ['nombre' => 'Llantas de prensa nylamid',                       'slug' => 'Llantas-de-prensa-nylamid',                  'mayoreo' => 1, 'precio' => 330,            'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 7.5,'alto' => 4, 'largo' => 7.5, 'peso' => 0.255],
                //['nombre' => '',                      'slug' => '',                      'mayoreo' => 0, 'precio' => ,              'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6],

                //Yoga
                ['nombre' => 'Aros de pilates',                     'slug' => 'Aros-de-pilates',                'mayoreo' => 0, 'precio' => 254.00,         'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 7,'ancho' => 37,'alto' => 5, 'largo' => 40, 'peso' => 0.245],
                ['nombre' => 'Bloque de yoga chico',                'slug' => 'Bloque-de-yoga-ch',              'mayoreo' => 0, 'precio' => 122.00,         'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 7,'ancho' => 14,'alto' => 7, 'largo' => 22, 'peso' => 0.13],
                ['nombre' => 'Bloque de yoga grande',               'slug' => 'Bloque-de-yoga-g',               'mayoreo' => 0, 'precio' => 146.00,         'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 7,'ancho' => 14,'alto' => 10, 'largo' => 22, 'peso' => 0.2],
                ['nombre' => 'Cinta para pilates 190 cm',           'slug' => 'Cinta-para-pilates-190-cm',      'mayoreo' => 0, 'precio' => 150.00,         'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 7,'ancho' => 6,'alto' => 3.2, 'largo' => 7, 'peso' => 0.1],
                ['nombre' => 'Rodillo de yoga',                     'slug' => 'Rodillo- de-yoga',               'mayoreo' => 0, 'precio' => 289.00,         'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 7,'ancho' => 13,'alto' => 13, 'largo' => 32, 'peso' => 0.87],
                ['nombre' => 'Aros de yoga',                        'slug' => 'Aros-de-yoga',                   'mayoreo' => 0, 'precio' => 370.00,         'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 7,'ancho' => 32,'alto' => 12.5, 'largo' => 32, 'peso' => 0.117],
                ['nombre' => 'Tapete yoga sencillo',                'slug' => 'Tapete-yoga-sencillo',           'mayoreo' => 0, 'precio' => 278.00,         'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 7,'ancho' => 11.5,'alto' => 11.5, 'largo' => 61, 'peso' => 0.915],
                ['nombre' => 'Tapete yoga doble cara',              'slug' => 'Tapete-yoga-doble-cara',         'mayoreo' => 0, 'precio' => 365.00,         'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 7,'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Cinta de elongación',                 'slug' => 'Cinta-de-elongacion',            'mayoreo' => 0, 'precio' => 254.00,         'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 7,'ancho' => 5,'alto' => 3.5, 'largo' => 19, 'peso' => 0.12],
                ['nombre' => 'Mini bossu par',                      'slug' => 'Mini-bossu',                     'mayoreo' => 0, 'precio' => 266.00,         'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 7,'ancho' => 16,'alto' => 20, 'largo' => 16, 'peso' => 0.5],
                //['nombre' => '', 'slug' => '', 'mayoreo' => 0, 'precio' => , 'precio_mayoreo' => null, 'category_id' => 7],

                //Straps
                ['nombre' => 'Straps sencilla de cinta',        'slug' => 'Straps-sencilla-de-cinta',       'mayoreo' => 0, 'precio' => 150.00,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 8,'ancho' => 10,'alto' => 4, 'largo' => 16, 'peso' => 0.065],
                ['nombre' => 'Straps con muñequera ajustable',  'slug' => 'Straps-con-munequera-ajustable', 'mayoreo' => 0, 'precio' => 196.00,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 8,'ancho' => 10,'alto' => 4, 'largo' => 17, 'peso' => 0.1],
                ['nombre' => 'Rodillera elastic',               'slug' => 'Rodillera-elastic',              'mayoreo' => 0, 'precio' => 284.00,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 8,'ancho' => 9,'alto' => 9, 'largo' => 9, 'peso' => 0.165],
                ['nombre' => 'Guantes de agarre multiusos',     'slug' => 'Guantes-de-agarre-multiusos',    'mayoreo' => 0, 'precio' => 145.00,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 8,'ancho' => 11,'alto' => 4, 'largo' => 14, 'peso' => 0.058],
                ['nombre' => 'Grilletes basicos',               'slug' => 'Grilletes-basicos',              'mayoreo' => 0, 'precio' => 138.00,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 8,'ancho' => 10,'alto' => 3, 'largo' => 13, 'peso' => 0.11],
                ['nombre' => 'Callera doble D',                 'slug' => 'Callera-doble-D',                'mayoreo' => 0, 'precio' => 244.00,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 8,'ancho' => 5,'alto' => 5, 'largo' => 12, 'peso' => 0.044],
                ['nombre' => 'Muñequera elastic',               'slug' => 'Munequera-elastic',              'mayoreo' => 0, 'precio' => 215.00,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 8,'ancho' => 8,'alto' => 8, 'largo' => 8, 'peso' => 0.084],
                ['nombre' => 'Grilletes 3 argollas',            'slug' => 'Grilletes-3-argollas',           'mayoreo' => 0, 'precio' => 322.00,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 8,'ancho' => 9,'alto' => 3, 'largo' => 13, 'peso' => 0.145],
                ['nombre' => 'Rodilleras twerk',                'slug' => 'Rodilleras-twerk',               'mayoreo' => 0, 'precio' => 220.00,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 8,'ancho' => 23,'alto' => 5, 'largo' => 27, 'peso' =>0.39 ],
                ['nombre' => 'Bandas de oclusión',              'slug' => 'Bandas-de-oclusion',             'mayoreo' => 0, 'precio' => 289.00,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 8,'ancho' => 7,'alto' => 3.5, 'largo' => 25, 'peso' => 0.11],
                ['nombre' => 'Faja moldeadora',                 'slug' => 'Faja-moldeadora',                'mayoreo' => 0, 'precio' => 405.00,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 8,'ancho' => 17,'alto' => 3, 'largo' => 26, 'peso' => 0.4],
                ['nombre' => 'Grilletes uso rudo',              'slug' => 'Grilletes-uso-rudo',             'mayoreo' => 0, 'precio' => 219.00,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 8,'ancho' => 11,'alto' => 5.5, 'largo' => 14, 'peso' => 0.2],
                ['nombre' => 'Grilletes de cuero',              'slug' => 'Grilletes-de-cuero',             'mayoreo' => 0, 'precio' => 557,                'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 8,'ancho' => 6,'alto' => 9, 'largo' => 34, 'peso' => 0.41],
                ['nombre' => 'Faja de cuero',                   'slug' => 'Faja-de-cuero',                  'mayoreo' => 0, 'precio' => 950,                'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 8,'ancho' => 5,'alto' => 10.5, 'largo' => 35, 'peso' => 0.35],
                ['nombre' => 'Guantes de peso',                 'slug' => 'Guantes-de-peso',                'mayoreo' => 0, 'precio' => 292.00,             'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 8,'ancho' => 9,'alto' => 6, 'largo' => 18, 'peso' => 0.6],
                ['nombre' => 'Straps premium',                  'slug' => 'Straps-premium',                 'mayoreo' => 0, 'precio' => 266,                'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 8,'ancho' => 9,'alto' => 5, 'largo' => 19, 'peso' => 0.125],
                //['nombre' => '', 'slug' => '', 'mayoreo' => 0, 'precio' => , 'precio_mayoreo' => null, 'category_id' => 8],


                ['nombre' => 'Cable con forro pvc',                     'slug' => 'Cable-con-forro-pvc-x-metro',               'mayoreo' => 1, 'precio' => 40,             'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 28,'alto' => 0.35, 'largo' => 28, 'peso' => 0.055],
                //longitudes cable 
                ['nombre' => 'Cable con forro pvc bobina',              'slug' => 'Cable-con-forro-pvc-bobina',                'mayoreo' => 1, 'precio' => 4000,           'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,'ancho' => 24,'alto' => 22, 'largo' => 24, 'peso' =>9.2],
                ['nombre' => 'Buje 1 1/4',              'slug' => 'Buje-1-1-4',                'mayoreo' => 0, 'precio' => 47,           'variante' => 0,    'precio_mayoreo' => null, 'category_id' => 6,  'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null],
                ['nombre' => 'Campana',              'slug' => 'Campana',                'mayoreo' => 0, 'precio' => 41,           'variante' => 1,    'precio_mayoreo' => null, 'category_id' => 6,        'ancho' => null,'alto' => null, 'largo' => null, 'peso' => null ],

            ])->map(function ($item) {
                $item['precio'] = round($item['precio'] * 1.16, 2); // Incrementa 16% y redondea a 2 decimales
                return $item;
            })->toArray()
        );
    }
}
